name: gemini ci
on:
  push:
    branches: [ masterr ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Execute ssh command via using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.CICD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin master

      - name: Notify about successful code deployment
        if: success()
        uses: Integrations-dev/GitHub-Informer@v1
        with:
          channel-endpoint: ${{ secrets.ENDPOINT }}
          message: 'Code deployed successfully to the master branch by ${{ github.actor }}.'

      - name: Call Gemini API
        if: success()
        run: |
          curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=GEMINI_API_KEY" \
          -H 'Content-Type: application/json' \
          -X POST \
          -d '{
          "contents": [{
          "parts":[{"text": "Explain how AI works"}]
          }]
          }'
