name: gemini ci

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Execute ssh command via using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.CICD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
            cd ${{ secrets.REMOTE_TARGET }}
            git pull origin masterr

      # Notify on fail
      - name: Notify on failure (Zoho Cliq & Gemini AI)
        if: failure()
        run: |
          # Notify on Zoho Cliq
          curl -X POST -H "Content-Type: application/json" -d '{"text":"❌❌❌GitHub Action Deployment failed❌❌❌ for branch ${{ github.ref }} in repository ${{ github.repository }}"}' "https://cliq.zoho.com/company/654406765/api/v2/channelsbyname/testingchannel/message?zapikey=${{ secrets.CLIQ_API_KEY }}"

          # Notify on Gemini AI (Assuming an API endpoint for Gemini AI exists)
          curl -X POST -H "Content-Type: application/json" -d '{
            "error_message": "GitHub CI build failed for branch ${{ github.ref }} in repository ${{ github.repository }}",
            "error_details": "${{ github.event.head_commit.message }}",
            "action": "deployment",
            "status": "failed"
          }' "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=GEMINI_API_KEY"

      # Example: Notify on success
      - name: Notify on success (Zoho Cliq)
        if: success()
        run: |
            curl -X POST -H "Content-Type: application/json" -d '{"text":"✅✅✅GitHub Action Deployment passed for branch ${{ github.ref }} in repository ${{ github.repository }}"}' "https://cliq.zoho.com/company/654406765/api/v2/channelsbyname/testingchannel/message?zapikey=${{ secrets.CLIQ_API_KEY }}"
