name: Gemini CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install SSH Agent
        uses: adriankth/setup-ssh@v2
        with:
          github-ssh: true

      - name: Add SSH Key
        run: |
          echo "${{ secrets.CICD_SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.PORT }} << EOF
          pwd
          cd ${{ secrets.REMOTE_TARGET }}
          git pull origin master
          EOF

      - name: Notify on Failure (Zoho Cliq)
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
              -d '{
                  "message": "❌❌❌ GitHub Action Deployment failed for branch ${{ github.ref }} in repository ${{ github.repository }}",
                  "parts": [
                    {
                      "text": "**Deployment Error Details:**",
                      "style": "BOLD"
                    },
                    {
                      "text": "```\n"
                    },
                    {
                      "text": "${{ steps.Deploy\ via\ SSH.outputs.error }}" 
                    },
                    {
                      "text": "```"
                    }
                  ]
              }' \
              "https://cliq.zoho.com/api/v2/channelsbyname/testingchannel/message?zapikey=${{ secrets.CLIQ_API_KEY }}"

      - name: Notify on Success (Gemini AI)
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
              -d '{
                  "contents": [
                    {
                      "parts": [
                        {
                          "text": "GitHub Action Deployment successful for branch ${{ github.ref }} in repository ${{ github.repository }}."
                        }
                      ]
                    }
                  ]
              }' \
              "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${{ secrets.GEMINI_API_KEY }}"
