name: Open Vpn

on:
  push:
    branches:
      - master
jobs:

  servostay-cicd:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '203.223.190.34'
          FILE_OVPN: '.github/config.ovpn'
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: kill vpn
        if: always()
        run: sudo killall openvpn
